header: # `header` section is configurations for source codes license header.
  license:
    spdx-id: GPL-3.0 # the spdx id of the license, it's convenient when your license is standard SPDX license.
    copyright-owner: CECTC # the copyright owner to replace the [owner] in the `spdx-id` template.
    content: | # `license` will be used as the content when `fix` command needs to insert a license header.
      This file is part of the hptx distribution (https://github.com/cectc/htpx).
      Copyright 2022 CECTC, Inc.
      
      This program is free software: you can redistribute it and/or modify it under the terms 
      of the GNU General Public License as published by the Free Software Foundation, either 
      version 3 of the License, or (at your option) any later version.
  
      This program is distributed in the hope that it will be useful, but 
      WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
      PARTICULAR PURPOSE. See the GNU General Public License for more details.
  
      You should have received a copy of the GNU General Public License along with this 
      program. If not, see <https://www.gnu.org/licenses/>.

    # `pattern` is optional regexp if all the file headers are the same as `license` or the license of `spdx-id` and `copyright-owner`.
    pattern:
  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - 'pkg/*'

  paths-ignore: # `paths-ignore` are the path list that will be ignored by license-eye.
    - 'pkg/api/api.proto'

  comment: on-failure # on what condition license-eye will comment on the pull request, `on-failure`, `always`, `never`.

  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language: # <10>
    Go: # <11>
      extensions: #<12>
        - ".go"
      comment_style_id: SlashAsterisk # <14>

dependency:
  files:
    - go.mod
